Use InClusterConfig when CreateKubeClient() was called without args
When `BuildConfigFromFlags(apiserver, kubeconfig)` was called with
empty apiserver and kubeconfig, it fallback to
rest.InClusterConfig(). When it happened, amazon-k8s-agent outputs
following warning message.

```
ERROR: logging before flag.Parse: W1217 10:37:25.707719      13 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

Although this error is harmless, it causes some confusion.

This patch changes to use `InClusterConfig()` when
`BuildConfigFromFlags` was called with empty args.

P.S `logging before flag.Parse` is also gone by this patch, as glog
is not called.